# Note: for exact transformations, use Yoshida order 2 because higher orders won't increase accuracy
@inline drift(tm::SciBmadStandard, p_over_q_ref, bunch, L) = drift(Yoshida(order=2), p_over_q_ref, bunch, L) 
@inline pure_patch(tm::SciBmadStandard, p_over_q_ref, bunch, patchparams, L) = pure_patch(Exact(), p_over_q_ref, bunch, patchparams, L)

@inline pure_rf(tm::SciBmadStandard, p_over_q_ref, bunch, rfparams, beamlineparams, L)                = pure_rf(Yoshida(), p_over_q_ref, bunch, rfparams, beamlineparams, L)                        
@inline pure_bsolenoid(tm::SciBmadStandard, p_over_q_ref, bunch, bm0, L)                              = pure_bsolenoid(Yoshida(order=2), p_over_q_ref, bunch, bm0, L)                             
@inline bsolenoid(tm::SciBmadStandard, p_over_q_ref, bunch, bmultipoleparams, L)                      = bsolenoid(Yoshida(), p_over_q_ref, bunch, bmultipoleparams, L)                     
@inline pure_bdipole(tm::SciBmadStandard, p_over_q_ref, bunch, bm1, L)                                = pure_bdipole(Yoshida(order=2), p_over_q_ref, bunch, bm1, L)                               
@inline bdipole(tm::SciBmadStandard, p_over_q_ref, bunch, bmultipoleparams, L)                        = bdipole(Yoshida(), p_over_q_ref, bunch, bmultipoleparams, L)                       
@inline pure_bquadrupole(tm::SciBmadStandard, p_over_q_ref, bunch, bm2, L)                            = pure_bquadrupole(Yoshida(), p_over_q_ref, bunch, bm2, L)                           
@inline bquadrupole(tm::SciBmadStandard, p_over_q_ref, bunch, bmultipoleparams, L)                    = bquadrupole(Yoshida(), p_over_q_ref, bunch, bmultipoleparams, L)                   
@inline pure_bmultipole(tm::SciBmadStandard, p_over_q_ref, bunch, bmk, L)                             = pure_bmultipole(Yoshida(), p_over_q_ref, bunch, bmk, L)                            
@inline bmultipole(tm::SciBmadStandard, p_over_q_ref, bunch, bmultipoleparams, L)                     = bmultipole(Yoshida(), p_over_q_ref, bunch, bmultipoleparams, L)                    
@inline bmultipole_rf(tm::SciBmadStandard, p_over_q_ref, bunch, bmultipoleparams, rfparams, beamlineparams, L) = bmultipole_rf(Yoshida(), p_over_q_ref, bunch, bmultipoleparams, rfparams, beamlineparams, L)
@inline bend_no_field(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, L)                        = bend_no_field(Yoshida(), p_over_q_ref, bunch, bendparams, L)                       
@inline bend_pure_bsolenoid(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bm0, L)             = bend_pure_bsolenoid(Yoshida(), p_over_q_ref, bunch, bendparams, bm0, L)            
@inline bend_bsolenoid(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bmultipoleparams, L)     = bend_bsolenoid(Yoshida(), p_over_q_ref, bunch, bendparams, bmultipoleparams, L)    
@inline bend_pure_bdipole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bm1, L)               = bend_pure_bdipole(Yoshida(), p_over_q_ref, bunch, bendparams, bm1, L)              
@inline bend_bdipole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bmultipoleparams, L)       = bend_bdipole(Yoshida(), p_over_q_ref, bunch, bendparams, bmultipoleparams, L)      
@inline bend_pure_bquadrupole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bm2, L)           = bend_pure_bquadrupole(Yoshida(), p_over_q_ref, bunch, bendparams, bm2, L)          
@inline bend_bquadrupole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bmultipoleparams, L)   = bend_bquadrupole(Yoshida(), p_over_q_ref, bunch, bendparams, bmultipoleparams, L)  
@inline bend_pure_bmultipole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bmk, L)            = bend_pure_bmultipole(Yoshida(), p_over_q_ref, bunch, bendparams, bmk, L)           
@inline bend_bmultipole(tm::SciBmadStandard, p_over_q_ref, bunch, bendparams, bmultipoleparams, L)    = bend_bmultipole(Yoshida(), p_over_q_ref, bunch, bendparams, bmultipoleparams, L)         
@inline implicit_in(tm::SciBmadStandard, p_over_q_ref, bunch, L) = implicit_in(Yoshida(), p_over_q_ref, bunch, L)
@inline implicit_body(tm::SciBmadStandard, p_over_q_ref, bunch, fourpotentialparams, bendparams, L) = implicit_body(Yoshida(), p_over_q_ref, bunch, fourpotentialparams, bendparams, L)
@inline implicit_out(tm::SciBmadStandard, p_over_q_ref, bunch, L) = implicit_out(Yoshida(), p_over_q_ref, bunch, L)